-- Generated by nwg-displays on 2026-09-17 at 17:30:17. Do not edit manually.

hl.monitor({
    output = "desc:LG Display 0x0762",
    mode = "1920x1080@60.02",
    position = "3640x360",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL S2722DC 8KY2HD3",
    mode = "2560x1440@59.95",
    position = "1080x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:Dell Inc. DELL S2421HS 3PPZ7P3",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0,
    transform = 3
})
